version: '3.8'

services:
  server:
    image: server:0.0.1
    ports:
      - "8080:8080"
    networks:
      - webnet

  prometheus:
    image: prom/prometheus:v2.40.7
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - webnet
    depends_on:
      - server

  grafana:
    image: grafana/grafana:9.4.2
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3080:3080"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
